//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosOP1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Empleado", Schema = "CT")]
    public partial class Empleado
    {
        public Empleado()
        {
            this.Contratacion = new HashSet<Contratacion>();
        }
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(8, ErrorMessage = "Longiturd maxima 8 caracteres")]
        [Display(Name = "Numero de Inss")]
        public string Inss { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(30, ErrorMessage = "Longiturd maxima 30 caracteres")]
        [Display(Name = "Nombre")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(30, ErrorMessage = "Longiturd maxima 30 caracteres")]
        [Display(Name = "Primer Apellido")]
        public string Apellido1 { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(30, ErrorMessage = "Longiturd maxima 30 caracteres")]
        [Display(Name = "Segundo Apellido")]
        public string Apellido2 { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(100, ErrorMessage = "Longiturd maxima 100 caracteres")]
        [Display(Name = "Direccion")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(12, ErrorMessage = "Longiturd maxima 12 caracteres")]
        [Display(Name = "Primer Apellido")]
        public string Telefono { get; set; }
        [Required]
        [Display(Name = "IdMunicipio")]
        public int MunicipioId { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual ICollection<Contratacion> Contratacion { get; set; }
    }
}
