//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosOP1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Municipio", Schema = "CT")]
    public partial class Municipio
    {
        public Municipio()
        {
            this.Empleado = new HashSet<Empleado>();
        }
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(5, ErrorMessage = "Longiturd maxima 5 caracteres")]
        [Display(Name = "Codigo")]
        public string Codigo { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(40, ErrorMessage = "Longiturd maxima 40 caracteres")]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [Display(Name = "IdDepartamento")]
        public int DepartamentoId { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
