//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosOP1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TipoContrato", Schema = "CT")]

    public partial class TipoDeContrato
    {

        public TipoDeContrato()
        {
            this.Contratacion = new HashSet<Contratacion>();
        }
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(5, ErrorMessage = "Longiturd maxima 5 caracteres")]
        [Display(Name = "Codigo")]
        public string CodigoTipo { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(40, ErrorMessage = "Longiturd maxima 40 caracteres")]
        [Display(Name = "Tipo Descripcion")]
        public string DescripcionTipo { get; set; }
    
        public virtual ICollection<Contratacion> Contratacion { get; set; }
    }
}
