//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosOP1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Unidad", Schema = "CT")]

    public partial class Unidad
    {
        public Unidad()
        {
            this.Contratacion = new HashSet<Contratacion>();
        }
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(5, ErrorMessage = "Longiturd maxima 5 caracteres")]
        [Display(Name = "Codigo")]
        public string CodigoUnidad { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(8, ErrorMessage = "Longitud maxima 8 caracteres")]
        [Display(Name = "Descripcion Unidad")]
        public string DescripcionUnidad { get; set; }
    
        public virtual ICollection<Contratacion> Contratacion { get; set; }
    }
}
